module.exports = {
  MAIN_SHEET_ID: '1wujwCk2u_PPXKHxt3fZXKqST0E4iZWAkJ56t_ZX83Ks',
  MAIN_SHEET_NAME: 'Events',
  ANON_SHEET_ID: '1WD_dLwB8ob3J5eOCHRFPrnoWBwTYTKCKQiZPJl-Z1bY',
  ANON_SHEET_NAME: 'Sheet1',
  TOKEN_SHEET_ID: '1Sb-hzZ2XWxY1My0FOhy-i-VbUOz4kctdlWtwempmlk0',
  TOKEN_SHEET_NAME: 'ValidTokens'
};